import { readFileSync } from "node:fs";
import assert from "node:assert/strict";

const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(html, /const pressedKeys = new Set\(\);/);
assert.match(html, /function updateFlightControls\(delta\)/);
assert.match(html, /function updateHeroFrame\(\)/);
assert.match(html, /function updateCameraBasis\(\)/);
assert.match(html, /function updateHeroHeadPose\(\)/);
assert.match(html, /function updateChaseCamera\(\)/);
assert.match(html, /keydown/);
assert.match(html, /keyup/);
assert.match(html, /KeyW/);
assert.match(html, /KeyA/);
assert.match(html, /KeyS/);
assert.match(html, /KeyD/);
assert.match(html, /Space/);
assert.match(html, /ShiftLeft/);
assert.match(html, /function updateFlightTrail\(\)/);
assert.match(html, /<title>Invencível voando sobre São Paulo 🌍<\/title>/);
assert.match(html, /id="start-overlay"/);
assert.match(html, /id="fps-readout"/);
assert.match(html, /id="hour"[\s\S]*?value="12"/);
assert.match(html, /const INTRO_START_HEIGHT = 180000;/);
assert.match(html, /const INTRO_TARGET_HEIGHT = 1000;/);
assert.match(html, /const INTRO_CAMERA_START_DISTANCE = 260;/);
assert.match(html, /const INTRO_CAMERA_END_DISTANCE = 760;/);
assert.match(html, /const MOUSE_CAMERA_SENSITIVITY = 0\.0028;/);
assert.match(html, /const CAMERA_MOUSE_PITCH_MIN = -0\.32;/);
assert.match(html, /const CAMERA_MOUSE_PITCH_MAX = 0\.24;/);
assert.match(html, /const introState = \{/);
assert.match(html, /function startIntroFlight\(\)/);
assert.match(html, /function updateIntroFlight\(delta\)/);
assert.match(html, /function updateFpsReadout\(time\)/);
assert.match(html, /startOverlay\.addEventListener\("click", startIntroFlight\);/);
assert.match(html, /if \(!introState\.controlsEnabled\) return;/);
assert.doesNotMatch(html, /Ele comeca fora da Terra/);
assert.match(html, /const BIRD_MODEL_CANDIDATES = \[/);
assert.match(html, /\.\/assets\/models\/fly-hero\.glb/);
assert.match(html, /\.\/assets\/models\/Flamingo\.glb/);
assert.match(html, /\.\/assets\/models\/Stork\.glb/);
assert.match(html, /\.\/assets\/models\/Parrot\.glb/);
assert.match(html, /const HERO_SP_LAT = -23\.5505;/);
assert.match(html, /const HERO_SP_LON = -46\.6333;/);
assert.match(html, /const HERO_SP_HEIGHT = 2200;/);
assert.match(html, /function loadBirdModels\(\)/);
assert.match(html, /function spawnBird\(\)/);
assert.match(html, /function updateBirds\(delta\)/);
assert.match(html, /birdRoot/);
assert.match(html, /birdSpawnAt/);
assert.match(html, /birdModels/);
assert.match(html, /const windAudio = new Audio\("\.\/assets\/audio\/vento\.wav"\);/);
assert.match(html, /windAudio\.loop = true;/);
assert.match(html, /function startWindAudio\(\)/);
assert.match(html, /function handlePointerMove\(event\)/);
assert.match(html, /pointermove/);
assert.match(html, /cameraOrbit/);
assert.match(html, /cameraStableUp/);
assert.match(html, /camera\.up\.copy\(cameraStableUp\);/);
assert.match(html, /cameraStableForward\.projectOnPlane\(cameraStableUp\)/);
assert.doesNotMatch(html, /function handlePointerDown\(event\)/);
assert.match(html, /const DOUBLE_TAP_WINDOW_MS = 280;/);
assert.match(html, /const SUPERSONIC_SPEED = 2400;/);
assert.match(html, /const SUPERSONIC_CLIMB_SPEED = 2800;/);
assert.match(html, /const FLIGHT_MIN_HEIGHT = 100;/);
assert.match(html, /const FLIGHT_MAX_HEIGHT = 250000;/);
assert.match(html, /function triggerBoost\(code\)/);
assert.match(html, /boostUntil/);
assert.match(html, /climbBoostUntil/);
assert.match(html, /function addHeroLighting\(\)/);
assert.match(html, /function brightenHeroModel\(model\)/);
assert.match(html, /const HERO_SATURATION_BOOST = 0\.18;/);
assert.match(html, /new THREE\.PointLight\(0xffffff, 4, 9000\)/);
assert.match(html, /emissiveIntensity/);
assert.match(html, /const HERO_YAW_OFFSET = Math\.PI;/);
assert.match(html, /heroModel\.rotation\.y = HERO_YAW_OFFSET;/);
assert.match(html, /Head_06/);
assert.match(html, /NEck_05/);
assert.match(html, /placeHeroAboveSP/);
assert.match(html, /position camera above Sao Paulo/);
assert.match(html, /const params = \{ hourUTC: 12 \}; \/\/ 12:00 UTC = 9:00 AM Sao Paulo/);
assert.match(html, /const headPitchTarget = THREE\.MathUtils\.clamp\([\s\S]*?Math\.max\(-flight\.pitch,[\s\S]*?Math\.max\(flight\.pitch,[\s\S]*?\);/);
assert.match(html, /const headYawTarget = THREE\.MathUtils\.clamp\([\s\S]*?flight\.roll,[\s\S]*?-0\.28,[\s\S]*?0\.28,[\s\S]*?\);/);
assert.match(html, /const CAMERA_FOLLOW_DISTANCE = 650;/);
assert.match(html, /const CAMERA_FOLLOW_HEIGHT = 220;/);
assert.match(html, /const INTRO_CAMERA_LOOK_AHEAD = 120;/);
assert.match(html, /const speedRatio = THREE\.MathUtils\.clamp\([\s\S]*?Math\.abs\(flight\.speed\) \/ SUPERSONIC_SPEED,[\s\S]*?0,[\s\S]*?1,[\s\S]*?\);/);
assert.match(html, /const baseCruisePitch = -0\.05 - speedRatio \* 0\.18;/);
assert.match(html, /const boostPitch = -0\.08 - speedRatio \* 0\.34;/);
assert.match(html, /const normalFollowDistance = THREE\.MathUtils\.lerp\([\s\S]*?CAMERA_FOLLOW_DISTANCE,[\s\S]*?1400,[\s\S]*?speedRatio,[\s\S]*?\);/);
assert.match(html, /const normalFollowHeight = THREE\.MathUtils\.lerp\([\s\S]*?CAMERA_FOLLOW_HEIGHT,[\s\S]*?420,[\s\S]*?speedRatio,[\s\S]*?\);/);
assert.match(html, /const followDistance = introState\.controlsEnabled[\s\S]*?INTRO_CAMERA_START_DISTANCE,[\s\S]*?INTRO_CAMERA_END_DISTANCE,[\s\S]*?introCameraProgress,[\s\S]*?\);/);
assert.match(html, /const lookAheadDistance = introState\.controlsEnabled\s*\?\s*CAMERA_LOOK_AHEAD\s*:\s*INTRO_CAMERA_LOOK_AHEAD;/);
assert.match(html, /cameraLookTarget[\s\S]*?addScaledVector\(cameraStableForward,\s*lookAheadDistance\)/);
